spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharma_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jackson:
    parser:
      allow-comments: true